version: '2'
services:
  ovm-app:
    image: ovm
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ovm-postgresql:5432/OVM
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8246:8246
  ovm-postgresql:
    extends:
      file: postgresql.yml
      service: ovm-postgresql
